spring:
  application:
    name: demo
  security:
    user:
     name: admin
     password: admin

  Datasource:
    url: jdbc:postgresql://localhost:5432/security-demo
    username: postgres
    password: 1234

app:
  jwt:
    secret: '${app.jwt.secret}'

